//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuercusPedidos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuercusPedidosEntities : DbContext
    {
        public QuercusPedidosEntities()
            : base("name=QuercusPedidosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PedidoDetalleBar> PedidoDetalleBar { get; set; }
        public virtual DbSet<PedidoDetalleRes> PedidoDetalleRes { get; set; }
        public virtual DbSet<ProductoBar> ProductoBar { get; set; }
        public virtual DbSet<ProductoRes> ProductoRes { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Pedido> Pedido { get; set; }
    }
}
