//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuercusPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoDetalleBar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PedidoDetalleBar()
        {
            this.Pedido = new HashSet<Pedido>();
        }
    
        public int Id_BarDetalle { get; set; }
        public int Id_ProductoBar { get; set; }
        public int Cantidad { get; set; }
        public int CostoTotal { get; set; }
    
        public virtual ProductoBar ProductoBar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}
