//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuercusPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public int Id_Pedido { get; set; }
        public string Mesa { get; set; }
        public bool Estado { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Subtotal { get; set; }
        public int Iva { get; set; }
        public int Total { get; set; }
        public Nullable<int> Id_ResDetalle { get; set; }
        public Nullable<int> Id_ProductoRes { get; set; }
        public Nullable<int> Id_BarDetalle { get; set; }
        public Nullable<int> Id_ProductoBar { get; set; }
    
        public virtual PedidoDetalleRes PedidoDetalleRes { get; set; }
        public virtual PedidoDetalleBar PedidoDetalleBar { get; set; }
    }
}
